name: 'Load Container Action'

description: 'Imports the image build caches and loads them for Docker CLI'

inputs:
  osg_series:
    description: 'OSG release series used to install packages'
    required: true
  repo:
    description: 'Input string that gets passed along to the docker build args'
    required: true
  timestamp_tag:
    description: >-
      Timestamped tag name (e.g.,
      "opensciencegrid/osgvo-docker-pilot3.6-release-YYYYMMDD-hhmm")
      used to pass the Dockerfile as $TIMESTAMP_TAG
    required: false
    default: ''

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2

  - name: Import Docker images from cache
    uses: actions/cache@v2
    with:
      path: /tmp/.buildx-cache
      key: ${{ inputs.osg_series}}-${{ inputs.repo }}-buildx-${{ github.sha }}-${{ github.run_id }}

  - name: Load Docker images for use in Docker CLI
    uses: docker/build-push-action@v2.2.2
    with:
      push: False
      context: .
      build-args: |
        BASE_YUM_REPO=${{ inputs.repo }}
        BASE_OSG_SERIES=${{ inputs.osg_series }}
        TIMESTAMP_TAG=${{ inputs.timestamp_tag }}
      load: True # allow acces to built images through the Docker CLI
      tags: "latest"
      cache-from: type=local,src=/tmp/.buildx-cache

